# Copyright (C) 2018  Christian Berger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '2'

services:
  peak-gps:
    container_name: peak-gps
    image: chalmersrevere/opendlv-device-gps-peak-multi:v0.0.8
    restart: always
    network_mode: "host"
    privileged: true
    command: "--can=vcan0 --cid=91 --id=0"

  garmin-gps:
    container_name: garmin-gps
    image: chalmersrevere/opendlv-device-gps-nmea-multi:v0.0.16
    restart: always
    network_mode: "host"
    command: "--udp --nmea_ip=0.0.0.0 --nmea_port=9999 --cid=93 --id=1"

  peak-to-statsd:
    container_name: peak-to-statsd
    image: opendlv-monitor-statsd-peak:latest
    restart: always
    network_mode: "host"
    command: "--cid=91"

  influxdb:
    image: influxdb:1.7.5
    container_name: influxdb
    restart: always
    environment:
    - INFLUXDB_HTTP_BIND_ADDRESS=:2713
    - INFLUXDB_REPORTING_DISABLED=1
    ports:
    - "2713:2713"
    - "25826:25826/udp"
    volumes:
    - ./influxdb-data:/var/lib/influxdb
    - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    - ./influxdb/types.db:/usr/share/collectd/types.db:ro

  collectd:
    build:
      context: ./collectd
      dockerfile: Dockerfile.amd64
    container_name: collectd
    restart: always
    depends_on:
    - influxdb
    privileged: true
    network_mode: host
    volumes:
    - /proc:/mnt/proc:ro
    - /mnt:/data:ro
    - ./collectd/collectd.conf:/etc/collectd/collectd.conf

  grafana:
    image: grafana/grafana:6.1.3
    container_name: grafana
    restart: always
    depends_on:
    - influxdb
    links:
    - "influxdb"
    ports:
    - "2712:2712"
    environment:
    - GF_SERVER_HTTP_PORT=2712
    - GF_SECURITY_ADMIN_PASSWORD=adm!n321
    - GF_SESSION_COOKIE_NAME=grafana_eagle
    - GF_SERVER_PROTOCOL=http
    - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,pr0ps-trackmap-panel
    volumes:
    - ./grafana-data:/var/lib/grafana
    - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    - ./grafana/Eagle.json:/var/lib/grafana/dashboards/Eagle.json

  record-gps:
    container_name: record-gps
    image: chrberger/cluon-amd64:latest
    cpuset: "0"
    restart: always
    network_mode: "host"
    volumes:
    - /mnt/sdb1/data/upload:/upload
    working_dir: /upload
    cap_add:
    - SYS_NICE
    command: sh -c "nice -n -7 cluon-OD4toStdout --cid=91 > `date +%Y-%m-%d_%H%M%S-gps-speed-heading-satellites.rec`"

  record-gps-garmin:
    container_name: record-gps-garmin
    image: chrberger/cluon-amd64:latest
    cpuset: "0"
    restart: always
    network_mode: "host"
    volumes:
    - /mnt/sdb1/data/upload:/upload
    working_dir: /upload
    cap_add:
    - SYS_NICE
    command: sh -c "nice -n -8 cluon-OD4toStdout --cid=93 > `date +%Y-%m-%d_%H%M%S-gps-garmin.rec`"

